-- 코드를 작성해주세요
SELECT DISTINCT ID
FROM ECOLI_DATA 
WHERE PARENT_ID IN (
    SELECT B.ID
    FROM ECOLI_DATA AS A
    RIGHT JOIN ECOLI_DATA AS B
    ON A.ID = B.PARENT_ID
    WHERE A.PARENT_ID IS NULL AND B.PARENT_ID IS NOT NULL
)