-- 코드를 작성해주세요
SELECT COUNT(*) AS COUNT
FROM ECOLI_DATA
WHERE IF(MID(CONVERT(BIN(GENOTYPE), CHAR), LENGTH(CONVERT(BIN(GENOTYPE), CHAR)) - 1, 1) = '', '0', MID(CONVERT(BIN(GENOTYPE), CHAR), LENGTH(CONVERT(BIN(GENOTYPE), CHAR)) - 1, 1)) = '0' AND
(RIGHT(CONVERT(BIN(GENOTYPE), CHAR), 1) = '1' OR MID(CONVERT(BIN(GENOTYPE), CHAR), LENGTH(CONVERT(BIN(GENOTYPE), CHAR)) - 2, 1) = '1')
