-- 코드를 작성해주세요
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT DISTINCT(A.ITEM_ID)
    FROM ITEM_TREE AS A
    LEFT JOIN ITEM_TREE AS B
    ON A.ITEM_ID = B.PARENT_ITEM_ID
    WHERE B.ITEM_ID IS NULL
)
ORDER BY ITEM_ID DESC