-- 코드를 작성해주세요
SELECT ROUND(
(SELECT SUM(LENGTH) + (
    SELECT COUNT(*) * 10
    FROM FISH_INFO
    WHERE LENGTH IS NULL
) AS AVERAGE_LENGTH
FROM FISH_INFO
WHERE LENGTH IS NOT NULL) / count(*), 2) AS AVERAGE_LENGTH
FROM FISH_INFO
