-- 코드를 입력하세요
SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
from REST_INFO as A
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) as FAVORITES
    FROM REST_INFO
    group by FOOD_TYPE
) as B
ON A.FOOD_TYPE = B.FOOD_TYPE AND A.FAVORITES = B.FAVORITES
order by FOOD_TYPE DESC;