-- 코드를 입력하세요
SELECT B.USER_ID, B.NICKNAME, CONCAT(B.CITY, ' ', B.STREET_ADDRESS1, ' ', B.STREET_ADDRESS2) as '전체주소',
CONCAT(SUBSTRING(B.TLNO, 1, 3), '-', SUBSTRING(B.TLNO, 4, 4), '-', SUBSTRING(B.TLNO, 8, 4)) as '전화번호'
FROM USED_GOODS_BOARD as A
JOIN USED_GOODS_USER as B
ON A.WRITER_ID = B.USER_ID
group by A.WRITER_ID
having count(*) >= 3
order by B.USER_ID DESC;