-- 코드를 입력하세요
SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE), 2) as 'SCORE'
FROM REST_INFO as A
JOIN REST_REVIEW as B
ON A.REST_ID = B.REST_ID
where A.ADDRESS like '서울%'
group by A.REST_ID
order by SCORE DESC, A.FAVORITES DESC;