-- 코드를 입력하세요
SELECT YEAR(B.SALES_DATE) as 'YEAR', MONTH(B.SALES_DATE) as 'MONTH', A.GENDER, count(DISTINCT B.USER_ID) as 'USERS' 
FROM USER_INFO as A
JOIN ONLINE_SALE as B
ON A.USER_ID = B.USER_ID
where A.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
order by YEAR, MONTH, GENDER;