SELECT YEAR(o.SALES_DATE) as YEAR, MONTH(o.SALES_DATE) MONTH, count(DISTINCT o.USER_ID) as PUCHASED_USERS, ROUND(count(DISTINCT o.USER_ID) / (SELECT count(*) from USER_INFO where JOINED like '2021%'), 1) as PUCHASED_RATIO 
from ONLINE_SALE as o JOIN USER_INFO as u USING (USER_ID) 
where JOINED like '2021%'
group by YEAR, MONTH 
order by YEAR, MONTH