SELECT DATE_FORMAT(a.SALES_DATE, '%Y-%m-%d') as SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT from (
SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT from ONLINE_SALE
union
SELECT SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT from OFFLINE_SALE) as a where SALES_DATE like '2022-03%' order by a.SALES_DATE, a.PRODUCT_ID, a.USER_ID