-- 코드를 입력하세요
# SELECT T.HISTORY_ID, ROUND((T.DAILY_FEE * DD) - (T.DAILY_FEE * DD * DISCOUNT_RATE * 0.01), 0) AS FEE
# SELECT T.HISTORY_ID, ROUND((T.DAILY_FEE * DD * (IFNULL(DISCOUNT_RATE, 0) * 0.01)), 0) AS FEE
SELECT T.HISTORY_ID, (T.DAILY_FEE * DD) - ROUND(T.DAILY_FEE * DD * (IFNULL(DISCOUNT_RATE, 0) * 0.01), 0) AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
RIGHT JOIN (
    SELECT H.HISTORY_ID, C.CAR_TYPE, C.DAILY_FEE, 
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE NULL
        END AS DAY,
        DATEDIFF(END_DATE, START_DATE) + 1 AS DD
    FROM CAR_RENTAL_COMPANY_CAR AS C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
) AS T
ON P.DURATION_TYPE = T.DAY AND P.CAR_TYPE = T.CAR_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC