-- 코드를 입력하세요
SELECT A.FLAVOR 
FROM (
    SELECT SUM(TOTAL_ORDER) as TOTAL_ORDER, FLAVOR
    FROM FIRST_HALF 
    GROUP BY FLAVOR
    union
    SELECT SUM(TOTAL_ORDER) as TOTAL_ORDER, FLAVOR
    FROM JULY 
    GROUP BY FLAVOR
) as A
group by A.FLAVOR
order by SUM(A.TOTAL_ORDER) DESC
limit 3;