-- 코드를 입력하세요
SELECT B.USER_ID, B.NICKNAME, SUM(PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD as A
JOIN USED_GOODS_USER as B
ON A.WRITER_ID = B.USER_ID
WHERE A.STATUS = 'DONE'
group by A.WRITER_ID
having TOTAL_SALES >= 700000
order by TOTAL_SALES;