-- 코드를 작성해주세요
SELECT E.EMP_NO, E.EMP_NAME, 
    CASE
        WHEN SUM(SCORE) / 2 >= 96 THEN 'S'
        WHEN SUM(SCORE) / 2 >= 90 THEN 'A'
        WHEN SUM(SCORE) / 2 >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN SUM(SCORE) / 2 >= 96 THEN E.SAL * 0.2
        WHEN SUM(SCORE) / 2 >= 90 THEN E.SAL * 0.15
        WHEN SUM(SCORE) / 2 >= 80 THEN E.SAL * 0.1
        ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES AS E
JOIN HR_DEPARTMENT AS D
ON E.DEPT_ID = D.DEPT_ID
JOIN HR_GRADE AS G
ON E.EMP_NO = G.EMP_NO
GROUP BY E.EMP_NO
ORDER BY E.EMP_NO ASC