-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX_VALUE - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA AS a
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_VALUE FROM ECOLI_DATA GROUP BY YEAR(DIFFERENTIATION_DATE)) AS b
on YEAR(DIFFERENTIATION_DATE) = b.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC