-- 코드를 작성해주세요
SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM (
    SELECT *
    FROM FISH_INFO
    WHERE LENGTH IN (SELECT MAX(LENGTH)
        FROM FISH_INFO
        GROUP BY FISH_TYPE
    )
) as A
JOIN FISH_NAME_INFO as B
ON A.FISH_TYPE = B.FISH_TYPE
ORDER BY A.ID ASC