-- 코드를 작성해주세요
SELECT SUM(G.SCORE) as SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_EMPLOYEES as E
JOIN HR_GRADE as G
ON E.EMP_NO = G.EMP_NO
WHERE YEAR = '2022'
GROUP BY G.EMP_NO
ORDER BY SCORE DESC
LIMIT 1