-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', A.BOARD_ID, '/', B.FILE_ID, B.FILE_NAME, B.FILE_EXT) as 'FILE_PATH'
FROM USED_GOODS_BOARD as A
JOIN USED_GOODS_FILE as B
ON A.BOARD_ID = B.BOARD_ID
where 1
and A.VIEWS = (
    SELECT MAX(VIEWS)
    FROM USED_GOODS_BOARD
)
order by A.VIEWS DESC, B.FILE_ID DESC