-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
from BOOK as A
JOIN AUTHOR as B
ON A.AUTHOR_ID = B.AUTHOR_ID
where CATEGORY = '경제'
order by PUBLISHED_DATE;